#########################
#      DeathSpawn       #
#   aello development   #
#   https://aello.dev   #
#########################

## Messages ###
lang:
  teleported: "&6You awake in {SPAWN_NAME}."
  created: "&aSuccessfully created a death spawn at your location!"
  deleted: "&cSuccessfully deleted that death spawn!"
  noperms: "&cInsufficient permissions!"
  noexist: "&cThat spawn does not exist!"
  alreadyexist: "&cThat spawn already exists!"


# This section contains all of the death spawns
# Use /deathspawn create <name> in-game to automatically add a spawn
# Use /deathspawn remove <name> in-game to remove a spawn
# It is not advisable to manually edit this section.
spawns: